#!/bin/sh
A="on_Part2_PatchGroup_select_currentIndexChanged"; B="slotPart2SetPatch"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part2_Output_select_currentIndexChanged"; B="slotPart2SetOutputSelect"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part2_VoiceReserve_select_valueChanged"; B="slotPart2VoiceReserve"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part2_MidiChannel_select_valueChanged"; B="slotPart2SetMidiChannel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part2_PatchNumber_select_valueChanged"; B="slotPart2SetPatch"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part2_OutputLevel_select_valueChanged"; B="slotPart2SetOutputLevel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part2_ChorusSend_select_valueChanged"; B="slotPart2SetChorusSend"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part2_ReverbSend_select_valueChanged"; B="slotPart2SetReverbSend"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part2_HighLimit_select_valueChanged"; B="slotPart2HighLimit"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part2_Transpose_select_valueChanged"; B="slotPart2Transpose"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part2_LowLimit_select_valueChanged"; B="slotPart2LowLimit"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part2_ReceivePrgChg_enable_toggled"; B="slotPart2SetReceivePrgChg"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part2_ReceiveVolume_enable_toggled"; B="slotPart2SetReceiveVolume"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part2_TuneAdj_select_valueChanged"; B="slotPart2TuneAdj"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part2_ReceiveMidi_enable_toggled"; B="slotPart2SetReceiveMidi"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part2_ReceiveHold_enable_toggled"; B="slotPart2SetReceiveHold"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part2_Level_select_valueChanged"; B="slotPart2SetLevel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part2_Pan_select_valueChanged"; B="slotPart2SetPan"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part2_TestTone_switch_toggled"; B="slotPart2TestTone"; sed -i.BAK s/"$B"/"$A"/g $1

A="on_Part3_PatchGroup_select_currentIndexChanged"; B="slotPart3SetPatch"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part3_Output_select_currentIndexChanged"; B="slotPart3SetOutputSelect"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part3_VoiceReserve_select_valueChanged"; B="slotPart3VoiceReserve"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part3_MidiChannel_select_valueChanged"; B="slotPart3SetMidiChannel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part3_PatchNumber_select_valueChanged"; B="slotPart3SetPatch"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part3_OutputLevel_select_valueChanged"; B="slotPart3SetOutputLevel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part3_ChorusSend_select_valueChanged"; B="slotPart3SetChorusSend"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part3_ReverbSend_select_valueChanged"; B="slotPart3SetReverbSend"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part3_HighLimit_select_valueChanged"; B="slotPart3HighLimit"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part3_Transpose_select_valueChanged"; B="slotPart3Transpose"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part3_LowLimit_select_valueChanged"; B="slotPart3LowLimit"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part3_ReceivePrgChg_enable_toggled"; B="slotPart3SetReceivePrgChg"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part3_ReceiveVolume_enable_toggled"; B="slotPart3SetReceiveVolume"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part3_TuneAdj_select_valueChanged"; B="slotPart3TuneAdj"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part3_ReceiveMidi_enable_toggled"; B="slotPart3SetReceiveMidi"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part3_ReceiveHold_enable_toggled"; B="slotPart3SetReceiveHold"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part3_Level_select_valueChanged"; B="slotPart3SetLevel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part3_Pan_select_valueChanged"; B="slotPart3SetPan"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part3_TestTone_switch_toggled"; B="slotPart3TestTone"; sed -i.BAK s/"$B"/"$A"/g $1

A="on_Part4_PatchGroup_select_currentIndexChanged"; B="slotPart4SetPatch"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part4_Output_select_currentIndexChanged"; B="slotPart4SetOutputSelect"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part4_VoiceReserve_select_valueChanged"; B="slotPart4VoiceReserve"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part4_MidiChannel_select_valueChanged"; B="slotPart4SetMidiChannel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part4_PatchNumber_select_valueChanged"; B="slotPart4SetPatch"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part4_OutputLevel_select_valueChanged"; B="slotPart4SetOutputLevel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part4_ChorusSend_select_valueChanged"; B="slotPart4SetChorusSend"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part4_ReverbSend_select_valueChanged"; B="slotPart4SetReverbSend"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part4_HighLimit_select_valueChanged"; B="slotPart4HighLimit"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part4_Transpose_select_valueChanged"; B="slotPart4Transpose"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part4_LowLimit_select_valueChanged"; B="slotPart4LowLimit"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part4_ReceivePrgChg_enable_toggled"; B="slotPart4SetReceivePrgChg"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part4_ReceiveVolume_enable_toggled"; B="slotPart4SetReceiveVolume"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part4_TuneAdj_select_valueChanged"; B="slotPart4TuneAdj"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part4_ReceiveMidi_enable_toggled"; B="slotPart4SetReceiveMidi"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part4_ReceiveHold_enable_toggled"; B="slotPart4SetReceiveHold"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part4_Level_select_valueChanged"; B="slotPart4SetLevel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part4_Pan_select_valueChanged"; B="slotPart4SetPan"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part4_TestTone_switch_toggled"; B="slotPart4TestTone"; sed -i.BAK s/"$B"/"$A"/g $1

A="on_Part5_PatchGroup_select_currentIndexChanged"; B="slotPart5SetPatch"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part5_Output_select_currentIndexChanged"; B="slotPart5SetOutputSelect"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part5_VoiceReserve_select_valueChanged"; B="slotPart5VoiceReserve"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part5_MidiChannel_select_valueChanged"; B="slotPart5SetMidiChannel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part5_PatchNumber_select_valueChanged"; B="slotPart5SetPatch"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part5_OutputLevel_select_valueChanged"; B="slotPart5SetOutputLevel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part5_ChorusSend_select_valueChanged"; B="slotPart5SetChorusSend"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part5_ReverbSend_select_valueChanged"; B="slotPart5SetReverbSend"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part5_HighLimit_select_valueChanged"; B="slotPart5HighLimit"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part5_Transpose_select_valueChanged"; B="slotPart5Transpose"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part5_LowLimit_select_valueChanged"; B="slotPart5LowLimit"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part5_ReceivePrgChg_enable_toggled"; B="slotPart5SetReceivePrgChg"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part5_ReceiveVolume_enable_toggled"; B="slotPart5SetReceiveVolume"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part5_TuneAdj_select_valueChanged"; B="slotPart5TuneAdj"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part5_ReceiveMidi_enable_toggled"; B="slotPart5SetReceiveMidi"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part5_ReceiveHold_enable_toggled"; B="slotPart5SetReceiveHold"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part5_Level_select_valueChanged"; B="slotPart5SetLevel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part5_Pan_select_valueChanged"; B="slotPart5SetPan"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part5_TestTone_switch_toggled"; B="slotPart5TestTone"; sed -i.BAK s/"$B"/"$A"/g $1

A="on_Part6_PatchGroup_select_currentIndexChanged"; B="slotPart6SetPatch"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part6_Output_select_currentIndexChanged"; B="slotPart6SetOutputSelect"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part6_VoiceReserve_select_valueChanged"; B="slotPart6VoiceReserve"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part6_MidiChannel_select_valueChanged"; B="slotPart6SetMidiChannel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part6_PatchNumber_select_valueChanged"; B="slotPart6SetPatch"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part6_OutputLevel_select_valueChanged"; B="slotPart6SetOutputLevel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part6_ChorusSend_select_valueChanged"; B="slotPart6SetChorusSend"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part6_ReverbSend_select_valueChanged"; B="slotPart6SetReverbSend"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part6_HighLimit_select_valueChanged"; B="slotPart6HighLimit"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part6_Transpose_select_valueChanged"; B="slotPart6Transpose"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part6_LowLimit_select_valueChanged"; B="slotPart6LowLimit"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part6_ReceivePrgChg_enable_toggled"; B="slotPart6SetReceivePrgChg"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part6_ReceiveVolume_enable_toggled"; B="slotPart6SetReceiveVolume"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part6_TuneAdj_select_valueChanged"; B="slotPart6TuneAdj"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part6_ReceiveMidi_enable_toggled"; B="slotPart6SetReceiveMidi"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part6_ReceiveHold_enable_toggled"; B="slotPart6SetReceiveHold"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part6_Level_select_valueChanged"; B="slotPart6SetLevel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part6_Pan_select_valueChanged"; B="slotPart6SetPan"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part6_TestTone_switch_toggled"; B="slotPart6TestTone"; sed -i.BAK s/"$B"/"$A"/g $1

A="on_Part7_PatchGroup_select_currentIndexChanged"; B="slotPart7SetPatch"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part7_Output_select_currentIndexChanged"; B="slotPart7SetOutputSelect"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part7_VoiceReserve_select_valueChanged"; B="slotPart7VoiceReserve"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part7_MidiChannel_select_valueChanged"; B="slotPart7SetMidiChannel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part7_PatchNumber_select_valueChanged"; B="slotPart7SetPatch"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part7_OutputLevel_select_valueChanged"; B="slotPart7SetOutputLevel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part7_ChorusSend_select_valueChanged"; B="slotPart7SetChorusSend"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part7_ReverbSend_select_valueChanged"; B="slotPart7SetReverbSend"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part7_HighLimit_select_valueChanged"; B="slotPart7HighLimit"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part7_Transpose_select_valueChanged"; B="slotPart7Transpose"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part7_LowLimit_select_valueChanged"; B="slotPart7LowLimit"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part7_ReceivePrgChg_enable_toggled"; B="slotPart7SetReceivePrgChg"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part7_ReceiveVolume_enable_toggled"; B="slotPart7SetReceiveVolume"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part7_TuneAdj_select_valueChanged"; B="slotPart7TuneAdj"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part7_ReceiveMidi_enable_toggled"; B="slotPart7SetReceiveMidi"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part7_ReceiveHold_enable_toggled"; B="slotPart7SetReceiveHold"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part7_Level_select_valueChanged"; B="slotPart7SetLevel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part7_Pan_select_valueChanged"; B="slotPart7SetPan"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part7_TestTone_switch_toggled"; B="slotPart7TestTone"; sed -i.BAK s/"$B"/"$A"/g $1

A="on_Part8_PatchGroup_select_currentIndexChanged"; B="slotPart8SetPatch"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part8_Output_select_currentIndexChanged"; B="slotPart8SetOutputSelect"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part8_VoiceReserve_select_valueChanged"; B="slotPart8VoiceReserve"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part8_MidiChannel_select_valueChanged"; B="slotPart8SetMidiChannel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part8_PatchNumber_select_valueChanged"; B="slotPart8SetPatch"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part8_OutputLevel_select_valueChanged"; B="slotPart8SetOutputLevel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part8_ChorusSend_select_valueChanged"; B="slotPart8SetChorusSend"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part8_ReverbSend_select_valueChanged"; B="slotPart8SetReverbSend"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part8_HighLimit_select_valueChanged"; B="slotPart8HighLimit"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part8_Transpose_select_valueChanged"; B="slotPart8Transpose"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part8_LowLimit_select_valueChanged"; B="slotPart8LowLimit"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part8_ReceivePrgChg_enable_toggled"; B="slotPart8SetReceivePrgChg"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part8_ReceiveVolume_enable_toggled"; B="slotPart8SetReceiveVolume"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part8_TuneAdj_select_valueChanged"; B="slotPart8TuneAdj"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part8_ReceiveMidi_enable_toggled"; B="slotPart8SetReceiveMidi"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part8_ReceiveHold_enable_toggled"; B="slotPart8SetReceiveHold"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part8_Level_select_valueChanged"; B="slotPart8SetLevel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part8_Pan_select_valueChanged"; B="slotPart8SetPan"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part8_TestTone_switch_toggled"; B="slotPart8TestTone"; sed -i.BAK s/"$B"/"$A"/g $1

A="on_Part9_PatchGroup_select_currentIndexChanged"; B="slotPart9SetPatch"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part9_Output_select_currentIndexChanged"; B="slotPart9SetOutputSelect"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part9_VoiceReserve_select_valueChanged"; B="slotPart9VoiceReserve"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part9_MidiChannel_select_valueChanged"; B="slotPart9SetMidiChannel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part9_PatchNumber_select_valueChanged"; B="slotPart9SetPatch"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part9_OutputLevel_select_valueChanged"; B="slotPart9SetOutputLevel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part9_ChorusSend_select_valueChanged"; B="slotPart9SetChorusSend"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part9_ReverbSend_select_valueChanged"; B="slotPart9SetReverbSend"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part9_HighLimit_select_valueChanged"; B="slotPart9HighLimit"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part9_Transpose_select_valueChanged"; B="slotPart9Transpose"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part9_LowLimit_select_valueChanged"; B="slotPart9LowLimit"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part9_ReceivePrgChg_enable_toggled"; B="slotPart9SetReceivePrgChg"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part9_ReceiveVolume_enable_toggled"; B="slotPart9SetReceiveVolume"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part9_TuneAdj_select_valueChanged"; B="slotPart9TuneAdj"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part9_ReceiveMidi_enable_toggled"; B="slotPart9SetReceiveMidi"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part9_ReceiveHold_enable_toggled"; B="slotPart9SetReceiveHold"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part9_Level_select_valueChanged"; B="slotPart9SetLevel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part9_Pan_select_valueChanged"; B="slotPart9SetPan"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part9_TestTone_switch_toggled"; B="slotPart9TestTone"; sed -i.BAK s/"$B"/"$A"/g $1

A="on_Part10_PatchGroup_select_currentIndexChanged"; B="slotPart10SetPatch"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part10_Output_select_currentIndexChanged"; B="slotPart10SetOutputSelect"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part10_VoiceReserve_select_valueChanged"; B="slotPart10VoiceReserve"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part10_MidiChannel_select_valueChanged"; B="slotPart10SetMidiChannel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part10_PatchNumber_select_valueChanged"; B="slotPart10SetPatch"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part10_OutputLevel_select_valueChanged"; B="slotPart10SetOutputLevel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part10_ChorusSend_select_valueChanged"; B="slotPart10SetChorusSend"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part10_ReverbSend_select_valueChanged"; B="slotPart10SetReverbSend"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part10_HighLimit_select_valueChanged"; B="slotPart10HighLimit"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part10_Transpose_select_valueChanged"; B="slotPart10Transpose"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part10_LowLimit_select_valueChanged"; B="slotPart10LowLimit"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part10_ReceivePrgChg_enable_toggled"; B="slotPart10SetReceivePrgChg"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part10_ReceiveVolume_enable_toggled"; B="slotPart10SetReceiveVolume"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part10_TuneAdj_select_valueChanged"; B="slotPart10TuneAdj"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part10_ReceiveMidi_enable_toggled"; B="slotPart10SetReceiveMidi"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part10_ReceiveHold_enable_toggled"; B="slotPart10SetReceiveHold"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part10_Level_select_valueChanged"; B="slotPart10SetLevel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part10_Pan_select_valueChanged"; B="slotPart10SetPan"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part10_TestTone_switch_toggled"; B="slotPart10TestTone"; sed -i.BAK s/"$B"/"$A"/g $1

A="on_Part11_PatchGroup_select_currentIndexChanged"; B="slotPart11SetPatch"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part11_Output_select_currentIndexChanged"; B="slotPart11SetOutputSelect"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part11_VoiceReserve_select_valueChanged"; B="slotPart11VoiceReserve"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part11_MidiChannel_select_valueChanged"; B="slotPart11SetMidiChannel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part11_PatchNumber_select_valueChanged"; B="slotPart11SetPatch"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part11_OutputLevel_select_valueChanged"; B="slotPart11SetOutputLevel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part11_ChorusSend_select_valueChanged"; B="slotPart11SetChorusSend"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part11_ReverbSend_select_valueChanged"; B="slotPart11SetReverbSend"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part11_HighLimit_select_valueChanged"; B="slotPart11HighLimit"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part11_Transpose_select_valueChanged"; B="slotPart11Transpose"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part11_LowLimit_select_valueChanged"; B="slotPart11LowLimit"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part11_ReceivePrgChg_enable_toggled"; B="slotPart11SetReceivePrgChg"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part11_ReceiveVolume_enable_toggled"; B="slotPart11SetReceiveVolume"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part11_TuneAdj_select_valueChanged"; B="slotPart11TuneAdj"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part11_ReceiveMidi_enable_toggled"; B="slotPart11SetReceiveMidi"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part11_ReceiveHold_enable_toggled"; B="slotPart11SetReceiveHold"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part11_Level_select_valueChanged"; B="slotPart11SetLevel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part11_Pan_select_valueChanged"; B="slotPart11SetPan"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part11_TestTone_switch_toggled"; B="slotPart11TestTone"; sed -i.BAK s/"$B"/"$A"/g $1

A="on_Part12_PatchGroup_select_currentIndexChanged"; B="slotPart12SetPatch"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part12_Output_select_currentIndexChanged"; B="slotPart12SetOutputSelect"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part12_VoiceReserve_select_valueChanged"; B="slotPart12VoiceReserve"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part12_MidiChannel_select_valueChanged"; B="slotPart12SetMidiChannel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part12_PatchNumber_select_valueChanged"; B="slotPart12SetPatch"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part12_OutputLevel_select_valueChanged"; B="slotPart12SetOutputLevel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part12_ChorusSend_select_valueChanged"; B="slotPart12SetChorusSend"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part12_ReverbSend_select_valueChanged"; B="slotPart12SetReverbSend"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part12_HighLimit_select_valueChanged"; B="slotPart12HighLimit"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part12_Transpose_select_valueChanged"; B="slotPart12Transpose"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part12_LowLimit_select_valueChanged"; B="slotPart12LowLimit"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part12_ReceivePrgChg_enable_toggled"; B="slotPart12SetReceivePrgChg"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part12_ReceiveVolume_enable_toggled"; B="slotPart12SetReceiveVolume"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part12_TuneAdj_select_valueChanged"; B="slotPart12TuneAdj"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part12_ReceiveMidi_enable_toggled"; B="slotPart12SetReceiveMidi"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part12_ReceiveHold_enable_toggled"; B="slotPart12SetReceiveHold"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part12_Level_select_valueChanged"; B="slotPart12SetLevel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part12_Pan_select_valueChanged"; B="slotPart12SetPan"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part12_TestTone_switch_toggled"; B="slotPart12TestTone"; sed -i.BAK s/"$B"/"$A"/g $1

A="on_Part13_PatchGroup_select_currentIndexChanged"; B="slotPart13SetPatch"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part13_Output_select_currentIndexChanged"; B="slotPart13SetOutputSelect"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part13_VoiceReserve_select_valueChanged"; B="slotPart13VoiceReserve"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part13_MidiChannel_select_valueChanged"; B="slotPart13SetMidiChannel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part13_PatchNumber_select_valueChanged"; B="slotPart13SetPatch"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part13_OutputLevel_select_valueChanged"; B="slotPart13SetOutputLevel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part13_ChorusSend_select_valueChanged"; B="slotPart13SetChorusSend"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part13_ReverbSend_select_valueChanged"; B="slotPart13SetReverbSend"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part13_HighLimit_select_valueChanged"; B="slotPart13HighLimit"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part13_Transpose_select_valueChanged"; B="slotPart13Transpose"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part13_LowLimit_select_valueChanged"; B="slotPart13LowLimit"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part13_ReceivePrgChg_enable_toggled"; B="slotPart13SetReceivePrgChg"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part13_ReceiveVolume_enable_toggled"; B="slotPart13SetReceiveVolume"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part13_TuneAdj_select_valueChanged"; B="slotPart13TuneAdj"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part13_ReceiveMidi_enable_toggled"; B="slotPart13SetReceiveMidi"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part13_ReceiveHold_enable_toggled"; B="slotPart13SetReceiveHold"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part13_Level_select_valueChanged"; B="slotPart13SetLevel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part13_Pan_select_valueChanged"; B="slotPart13SetPan"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part13_TestTone_switch_toggled"; B="slotPart13TestTone"; sed -i.BAK s/"$B"/"$A"/g $1

A="on_Part14_PatchGroup_select_currentIndexChanged"; B="slotPart14SetPatch"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part14_Output_select_currentIndexChanged"; B="slotPart14SetOutputSelect"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part14_VoiceReserve_select_valueChanged"; B="slotPart14VoiceReserve"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part14_MidiChannel_select_valueChanged"; B="slotPart14SetMidiChannel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part14_PatchNumber_select_valueChanged"; B="slotPart14SetPatch"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part14_OutputLevel_select_valueChanged"; B="slotPart14SetOutputLevel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part14_ChorusSend_select_valueChanged"; B="slotPart14SetChorusSend"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part14_ReverbSend_select_valueChanged"; B="slotPart14SetReverbSend"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part14_HighLimit_select_valueChanged"; B="slotPart14HighLimit"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part14_Transpose_select_valueChanged"; B="slotPart14Transpose"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part14_LowLimit_select_valueChanged"; B="slotPart14LowLimit"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part14_ReceivePrgChg_enable_toggled"; B="slotPart14SetReceivePrgChg"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part14_ReceiveVolume_enable_toggled"; B="slotPart14SetReceiveVolume"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part14_TuneAdj_select_valueChanged"; B="slotPart14TuneAdj"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part14_ReceiveMidi_enable_toggled"; B="slotPart14SetReceiveMidi"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part14_ReceiveHold_enable_toggled"; B="slotPart14SetReceiveHold"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part14_Level_select_valueChanged"; B="slotPart14SetLevel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part14_Pan_select_valueChanged"; B="slotPart14SetPan"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part14_TestTone_switch_toggled"; B="slotPart14TestTone"; sed -i.BAK s/"$B"/"$A"/g $1

A="on_Part15_PatchGroup_select_currentIndexChanged"; B="slotPart15SetPatch"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part15_Output_select_currentIndexChanged"; B="slotPart15SetOutputSelect"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part15_VoiceReserve_select_valueChanged"; B="slotPart15VoiceReserve"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part15_MidiChannel_select_valueChanged"; B="slotPart15SetMidiChannel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part15_PatchNumber_select_valueChanged"; B="slotPart15SetPatch"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part15_OutputLevel_select_valueChanged"; B="slotPart15SetOutputLevel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part15_ChorusSend_select_valueChanged"; B="slotPart15SetChorusSend"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part15_ReverbSend_select_valueChanged"; B="slotPart15SetReverbSend"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part15_HighLimit_select_valueChanged"; B="slotPart15HighLimit"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part15_Transpose_select_valueChanged"; B="slotPart15Transpose"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part15_LowLimit_select_valueChanged"; B="slotPart15LowLimit"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part15_ReceivePrgChg_enable_toggled"; B="slotPart15SetReceivePrgChg"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part15_ReceiveVolume_enable_toggled"; B="slotPart15SetReceiveVolume"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part15_TuneAdj_select_valueChanged"; B="slotPart15TuneAdj"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part15_ReceiveMidi_enable_toggled"; B="slotPart15SetReceiveMidi"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part15_ReceiveHold_enable_toggled"; B="slotPart15SetReceiveHold"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part15_Level_select_valueChanged"; B="slotPart15SetLevel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part15_Pan_select_valueChanged"; B="slotPart15SetPan"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part15_TestTone_switch_toggled"; B="slotPart15TestTone"; sed -i.BAK s/"$B"/"$A"/g $1

A="on_Part16_PatchGroup_select_currentIndexChanged"; B="slotPart16SetPatch"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part16_Output_select_currentIndexChanged"; B="slotPart16SetOutputSelect"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part16_VoiceReserve_select_valueChanged"; B="slotPart16VoiceReserve"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part16_MidiChannel_select_valueChanged"; B="slotPart16SetMidiChannel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part16_PatchNumber_select_valueChanged"; B="slotPart16SetPatch"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part16_OutputLevel_select_valueChanged"; B="slotPart16SetOutputLevel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part16_ChorusSend_select_valueChanged"; B="slotPart16SetChorusSend"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part16_ReverbSend_select_valueChanged"; B="slotPart16SetReverbSend"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part16_HighLimit_select_valueChanged"; B="slotPart16HighLimit"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part16_Transpose_select_valueChanged"; B="slotPart16Transpose"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part16_LowLimit_select_valueChanged"; B="slotPart16LowLimit"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part16_ReceivePrgChg_enable_toggled"; B="slotPart16SetReceivePrgChg"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part16_ReceiveVolume_enable_toggled"; B="slotPart16SetReceiveVolume"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part16_TuneAdj_select_valueChanged"; B="slotPart16TuneAdj"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part16_ReceiveMidi_enable_toggled"; B="slotPart16SetReceiveMidi"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part16_ReceiveHold_enable_toggled"; B="slotPart16SetReceiveHold"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part16_Level_select_valueChanged"; B="slotPart16SetLevel"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part16_Pan_select_valueChanged"; B="slotPart16SetPan"; sed -i.BAK s/"$B"/"$A"/g $1
A="on_Part16_TestTone_switch_toggled"; B="slotPart16TestTone"; sed -i.BAK s/"$B"/"$A"/g $1

