#!/bin/sh
A="on_PatchEFX_ReverbHiFreqDamp_select_currentIndexChanged";B="slotPatchEFX_ReverbHiFreqDamp"; sed -i s/"$B"/"$A"/g $1
A="on_PatchEFX_Control1Source_select_currentIndexChanged";B="slotPatchEFX_Control1Source"; sed -i s/"$B"/"$A"/g $1
A="on_PatchEFX_Control2Source_select_currentIndexChanged";B="slotPatchEFX_Control2Source"; sed -i s/"$B"/"$A"/g $1
A="on_PatchEFX_ChorusOutput_select_currentIndexChanged";B="slotPatchEFX_ChorusOutput"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_ControlSource2_select_currentIndexChanged";B="slotPatch_ControlSource2"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_ControlSource3_select_currentIndexChanged";B="slotPatch_ControlSource3"; sed -i s/"$B"/"$A"/g $1
A="on_PatchEFX_ReverbType_select_currentIndexChanged";B="slotPatchEFX_ReverbType"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_C1_HoldPeak_select_currentIndexChanged";B="slotPatch_C1_HoldPeak"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_C2_HoldPeak_select_currentIndexChanged";B="slotPatch_C2_HoldPeak"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_C3_HoldPeak_select_currentIndexChanged";B="slotPatch_C3_HoldPeak"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_PerfPartNum_select_currentIndexChanged";B="slotPatch_PerfPartNum"; sed -i s/"$B"/"$A"/g $1
A="on_PatchEFX_ReverbFeedback_select_valueChanged";B="slotPatchEFX_ReverbFeedback"; sed -i s/"$B"/"$A"/g $1
A="on_PatchEFX_ChorusPreDelay_select_valueChanged";B="slotPatchEFX_ChorusPreDelay"; sed -i s/"$B"/"$A"/g $1
A="on_PatchEFX_ChorusFeedback_select_valueChanged";B="slotPatchEFX_ChorusFeedback"; sed -i s/"$B"/"$A"/g $1
A="on_PatchEFX_Control1Depth_select_valueChanged";B="slotPatchEFX_Control1Depth"; sed -i s/"$B"/"$A"/g $1
A="on_PatchEFX_Control2Depth_select_valueChanged";B="slotPatchEFX_Control2Depth"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_HoldPeak_select_currentIndexChanged";B="slotPatch_HoldPeak"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_PortamentoTime_select_valueChanged";B="slotPatch_PortamentoTime"; sed -i s/"$B"/"$A"/g $1
A="on_PatchEFX_ReverbLevel_select_valueChanged";B="slotPatchEFX_ReverbLevel"; sed -i s/"$B"/"$A"/g $1
A="on_PatchEFX_ChorusLevel_select_valueChanged";B="slotPatchEFX_ChorusLevel"; sed -i s/"$B"/"$A"/g $1
A="on_PatchEFX_ChorusDepth_select_valueChanged";B="slotPatchEFX_ChorusDepth"; sed -i s/"$B"/"$A"/g $1
A="on_PatchEFX_ReverbTime_select_valueChanged";B="slotPatchEFX_ReverbTime"; sed -i s/"$B"/"$A"/g $1
A="on_PatchEFX_ChorusRate_select_valueChanged";B="slotPatchEFX_ChorusRate"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_Group_select_currentIndexChanged";B="slotPatchGroup"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_PortamentoEnable_switch_toggled";B="slotPatch_PortamentoEnable"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_BenderDown_select_valueChanged";B="slotPatch_BenderDown"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_PortamentoStart_switch_toggled";B="slotPatch_PortamentoStart"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_AnalogFeel_select_valueChanged";B="slotPatch_AnalogFeel"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_Booster34_select_valueChanged";B="slotPatch_Booster34"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_Booster12_select_valueChanged";B="slotPatch_Booster12"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_Booster34_select_valueChanged";B="slotPatch_Booster34"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_PortamentoMode_switch_toggled";B="slotPatch_PortamentoMode"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_PortamentoType_switch_toggled";B="slotPatch_PortamentoType"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_BenderUp_select_valueChanged";B="slotPatch_BenderUp"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_Struct12_select_valueChanged";B="slotPatch_Struct12"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_Struct34_select_valueChanged";B="slotPatch_Struct34"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_VelocityRange_enable_toggled";B="slotPatch_VelocityRange"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_VoicePriority_switch_toggled";B="slotPatch_VoicePriority"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_Number_select_valueChanged";B="slotPatchNumber"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_SoloLegato_enable_toggled";B="slotPatch_SoloLegato"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_Name_edit_editingFinished";B="slotPatchName"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_Level_select_valueChanged";B="slotPatch_Level"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_VoiceMode_switch_toggled";B="slotPatch_VoiceMode"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_Pan_select_valueChanged";B="slotPatch_Pan"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_TestTone_switch_toggled";B="slotPatch_TestTone_switch"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_Tone1_enable_toggled";B="slotPatch_Tone1"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_Tone2_enable_toggled";B="slotPatch_Tone2"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_Tone3_enable_toggled";B="slotPatch_Tone3"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_Tone4_enable_toggled";B="slotPatch_Tone4"; sed -i s/"$B"/"$A"/g $1
A="on_Patch_Sync_button_clicked";B="slotPatchSync"; sed -i s/"$B"/"$A"/g $1
