#!/bin/sh
A="on_Rhythm_RandPitchDepth_select_currentIndexChanged";B="slotRhythm_RandPitchDepth"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_TVAVelTimeSens_select_currentIndexChanged";B="slotRhythm_TVAVelTimeSens"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_TVFVelTimeSens_select_currentIndexChanged";B="slotRhythm_TVFVelTimeSens"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_PitchVeloTime_select_currentIndexChanged";B="slotRhythm_PitchVeloTime"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_TVFFilterType_select_currentIndexChanged";B="slotRhythm_TVFFilterType"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_PanControl_select_currentIndexChanged";B="slotRhythm_PanControl"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_WaveGroup_select_currentIndexChanged";B="slotRhythm_WaveGroup"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_WaveGain_select_currentIndexChanged";B="slotRhythm_WaveGain"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_TVFResVelocSens_select_valueChanged";B="slotRhythm_TVFResVelocSens"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_PitchVelocSens_select_valueChanged";B="slotRhythm_PitchVelocSens"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_TVFCutoffFreq_select_valueChanged";B="slotRhythm_TVFCutoffFreq"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_SoundingPitch_select_valueChanged";B="slotRhythm_SoundingPitch"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_Output_select_currentIndexChanged";B="slotRhythm_Output"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_TVAVelocSens_select_valueChanged";B="slotRhythm_TVAVelocSens"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_TVFResonance_select_valueChanged";B="slotRhythm_TVFResonance"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_TVFVelocSens_select_valueChanged";B="slotRhythm_TVFVelocSens"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_PanRandDepth_select_valueChanged";B="slotRhythm_PanRandDepth"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_OutputLevel_select_valueChanged";B="slotRhythm_OutputLevel"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_BenderRange_select_valueChanged";B="slotRhythm_BenderRange"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_PitchTime1_select_valueChanged";B="slotRhythm_PitchTime1"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_PitchTime2_select_valueChanged";B="slotRhythm_PitchTime2"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_PitchTime3_select_valueChanged";B="slotRhythm_PitchTime3"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_PitchTime4_select_valueChanged";B="slotRhythm_PitchTime4"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_WaveNumber_select_valueChanged";B="slotRhythm_WaveNumber"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_PitchDepth_select_valueChanged";B="slotRhythm_PitchDepth"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_ChorusSend_select_valueChanged";B="slotRhythm_ChorusSend"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_ReverbSend_select_valueChanged";B="slotRhythm_ReverbSend"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_PitchLvl1_select_valueChanged";B="slotRhythm_PitchLvl1"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_PitchLvl2_select_valueChanged";B="slotRhythm_PitchLvl2"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_PitchLvl3_select_valueChanged";B="slotRhythm_PitchLvl3"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_PitchLvl4_select_valueChanged";B="slotRhythm_PitchLvl4"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_ToneLevel_select_valueChanged";B="slotRhythm_ToneLevel"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_MuteGroup_select_valueChanged";B="slotRhythm_MuteGroup"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_TVFDepth_select_valueChanged";B="slotRhythm_TVFDepth"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_KeyPress_select_valueChanged";B="slotRhythm_KeyPress"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_TVATime1_select_valueChanged";B="slotRhythm_TVATime1"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_TVATime2_select_valueChanged";B="slotRhythm_TVATime2"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_TVATime3_select_valueChanged";B="slotRhythm_TVATime3"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_TVATime4_select_valueChanged";B="slotRhythm_TVATime4"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_TVALvl1_select_valueChanged";B="slotRhythm_TVALvl1"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_TVALvl2_select_valueChanged";B="slotRhythm_TVALvl2"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_TVALvl3_select_valueChanged";B="slotRhythm_TVALvl3"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_TVFTime1_select_valueChanged";B="slotRhythm_TVFTime1"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_TVFTime2_select_valueChanged";B="slotRhythm_TVFTime2"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_TVFTime3_select_valueChanged";B="slotRhythm_TVFTime3"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_TVFTime4_select_valueChanged";B="slotRhythm_TVFTime4"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_TVFLvl2_select_valueChanged";B="slotRhythm_TVFLvl2"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_TVFLvl3_select_valueChanged";B="slotRhythm_TVFLvl3"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_TVFLvl4_select_valueChanged";B="slotRhythm_TVFLvl4"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_TVFLvl1_select_valueChanged";B="slotRhythm_TVFLvl1"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_TuneAdj_select_valueChanged";B="slotRhythm_TuneAdj"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_AltPan_select_valueChanged";B="slotRhythm_AltPan"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_Pan_select_valueChanged";B="slotRhythm_Pan"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_TestTone_switch_clicked";B="slotRhythm_TestTone"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_EnvMode_select_toggled";B="slotRhythm_EnvMode"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_Volume_enable_toggled";B="slotRhythm_Volume"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_Sync_button_clicked";B="slotRhythm_Sync"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_Note_enable_toggled";B="slotRhythm_Note"; sed -i s/"$B"/"$A"/g $1
A="on_Rhythm_Hold_enable_toggled";B="slotRhythm_Hold"; sed -i s/"$B"/"$A"/g $1
