#!/bin/sh
A="on_Tone_InstrFamily_select_currentIndexChanged";B="slotTone_InstrFamily"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_WaveChooser_select_currentIndexChanged";B="slotTone_WaveChooser"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_DelayMode_select_currentIndexChanged";B="slotTone_DelayMode"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_FXMColor_select_currentIndexChanged";B="slotTone_FXMColor"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_FXMDepth_select_currentIndexChanged";B="slotTone_FXMDepth"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_WaveGain_select_currentIndexChanged";B="slotTone_WaveGain"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_VeloXfadeDepth_select_valueChanged";B="slotTone_VeloXfadeDepth"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_VeloUpperRange_select_valueChanged";B="slotTone_VeloUpperRange"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_VeloLowerRange_select_valueChanged";B="slotTone_VeloLowerRange"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_Output_select_currentIndexChanged";B="slotTone_Output"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_Group_select_currentIndexChanged";B="slotTone_Group"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_C1D1_select_currentIndexChanged";B="slotTone_C1D1"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_C1D2_select_currentIndexChanged";B="slotTone_C1D2"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_C1D3_select_currentIndexChanged";B="slotTone_C1D3"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_C1D4_select_currentIndexChanged";B="slotTone_C1D4"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_C2D1_select_currentIndexChanged";B="slotTone_C2D1"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_C2D2_select_currentIndexChanged";B="slotTone_C2D2"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_C2D3_select_currentIndexChanged";B="slotTone_C2D3"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_C2D4_select_currentIndexChanged";B="slotTone_C2D4"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_C3D1_select_currentIndexChanged";B="slotTone_C3D1"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_C3D2_select_currentIndexChanged";B="slotTone_C3D2"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_C3D3_select_currentIndexChanged";B="slotTone_C3D3"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_C3D4_select_currentIndexChanged";B="slotTone_C3D4"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_OutputLevel_select_valueChanged";B="slotTone_OutputLevel"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_ToneNumber_select_valueChanged";B="slotTone_ToneNumber"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_ChorusSend_select_valueChanged";B="slotTone_ChorusSend"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_ReverbSend_select_valueChanged";B="slotTone_ReverbSend"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_ReceiveReDamper_enable_toggled";B="slotTone_ReceiveReDamper"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_DelayTime_select_valueChanged";B="slotTone_DelayTime"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_C1D1Depth_select_valueChanged";B="slotTone_C1D1Depth"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_C1D2Depth_select_valueChanged";B="slotTone_C1D2Depth"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_C1D3Depth_select_valueChanged";B="slotTone_C1D3Depth"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_C1D4Depth_select_valueChanged";B="slotTone_C1D4Depth"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_C2D1Depth_select_valueChanged";B="slotTone_C2D1Depth"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_C2D2Depth_select_valueChanged";B="slotTone_C2D2Depth"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_C2D3Depth_select_valueChanged";B="slotTone_C2D3Depth"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_C2D4Depth_select_valueChanged";B="slotTone_C2D4Depth"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_C3D1Depth_select_valueChanged";B="slotTone_C3D1Depth"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_C3D2Depth_select_valueChanged";B="slotTone_C3D2Depth"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_C3D3Depth_select_valueChanged";B="slotTone_C3D3Depth"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_C3D4Depth_select_valueChanged";B="slotTone_C3D4Depth"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_ReceiveVolume_enable_toggled";B="slotTone_ReceiveVolume"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_ReceiveBender_enable_toggled";B="slotTone_ReceiveBender"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_ReceiveHold_enable_toggled";B="slotTone_ReceiveHold"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_Number_select_valueChanged";B="slotTone_Number"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_Level_select_valueChanged";B="slotTone_Level"; sed -i s/"$B"/"$A"/g $1
A="on_Tone_FXM_enable_toggled";B="slotTone_FXM"; sed -i s/"$B"/"$A"/g $1
A="on_ToneSync_button_clicked";B="slotToneSync_button"; sed -i s/"$B"/"$A"/g $1
